### ISSUE TITLE
Gradle 5 support

### ISSUE THREAD

**Issue by soberich** [etiennestuder/gradle-credentials-plugin#24] opened 2018-11-08 03:45 UTC
With gradle 5 plugin fails. (at least when `addCredentials` executed)
This concludes all details )

**Comment by etiennestuder** [comment] 2018-11-10 09:43
Thanks for the report. I do not have time to look into this in the near future.

**Comment by alwyn** [comment] 2018-11-21 23:38
I started looking into this.  In the plug-in itself the issue is mostly dependencies on internal api's of gradle and groovy that in the case of gradle has been moved to be non-internal and groovy to be completely removed.

This and changing the build-scan version to 2.0.2 will get you building.

I'm getting with transitive dependencies and have just decided to role my own.  Maybe the preceding will point someone in the right direction.

**Comment by etiennestuder** [comment] 2019-01-11 05:44
Fixed. Will be released as version 1.0.5.

**Closed by etiennestuder** 2019-01-11 05:44 UTC
